services:
  - type: web
    name: jeu-bleu-rouge
    env: node
    buildCommand: rm -rf node_modules && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
